# Generated by Django 5.2.6 on 2025-10-01 11:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=100)),
                ('personnel_code', models.CharField(blank=True, max_length=50)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('leave_type', models.CharField(choices=[('PAID', 'Paid Leave'), ('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave')], max_length=12)),
                ('mode', models.CharField(choices=[('DAILY', 'Daily'), ('HOURLY', 'Hourly')], max_length=8)),
                ('daily_from', models.DateField(blank=True, null=True)),
                ('daily_to', models.DateField(blank=True, null=True)),
                ('duration_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('hourly_date', models.DateField(blank=True, null=True)),
                ('hourly_from', models.TimeField(blank=True, null=True)),
                ('hourly_to', models.TimeField(blank=True, null=True)),
                ('remaining_monthly_days', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('base_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='core.request')),
                ('replacement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_replacements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
