# Generated by Django 5.2.6 on 2025-10-02 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_request_required_user_alter_approval_decided_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='approval',
            name='decided_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Employee'), (2, 'Middle Management'), (3, 'Executive Management'), (4, 'Board of Directors')], null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='replacement',
            field=models.ForeignKey(blank=True, help_text='The person who will cover; they approve first.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_replacements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Middle Management'), (3, 'Executive Management'), (4, 'Board of Directors')], default=1),
        ),
        migrations.AlterField(
            model_name='request',
            name='required_role',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Middle Management'), (3, 'Executive Management'), (4, 'Board of Directors')], default=2, help_text='Next role tier after replacement.'),
        ),
        migrations.AlterField(
            model_name='request',
            name='required_user',
            field=models.ForeignKey(blank=True, help_text='If set, this specific user must act before role-based approvals.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_waiting_on_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
