# Generated by Django 5.2.6 on 2025-10-02 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_leaverequest_options_alter_profile_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='required_user',
            field=models.ForeignKey(blank=True, help_text='If set, this specific user must act before role-based approvers.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_to_approve', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approval',
            name='decided_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Board of Directors'), (2, 'Executive Management'), (3, 'Middle Management'), (4, 'Employee')], null=True),
        ),
    ]
