# Generated by Django 5.2.6 on 2026-05-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalanceadjustment',
            name='year',
            field=models.PositiveIntegerField(help_text='Calendar year this adjustment applies to.'),
        ),
    ]
