# Generated by Django 5.2.6 on 2026-06-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_leavebalanceadjustment_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='annual_leave_days',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Annual leave allowance for this employee. Default is 30 days.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalanceadjustment',
            name='delta_days',
            field=models.DecimalField(decimal_places=2, help_text='Use + to grant, minus to deduct.', max_digits=5),
        ),
    ]
