# Generated by Django 5.2.6 on 2026-06-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_profile_annual_leave_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='approved_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='cancelled_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='rejected_days',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
