# Generated by Django 5.2.6 on 2026-06-03 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_profile_approved_days_profile_cancelled_days_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavebalanceadjustment',
            name='delta_days',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='leavebalanceadjustment',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_replacements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='annual_leave_days',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='request',
            name='required_role',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Middle Management'), (3, 'Executive Management'), (4, 'Board of Directors')], default=2),
        ),
        migrations.AlterField(
            model_name='request',
            name='required_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_waiting_on_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
