# Generated by Django 5.2.6 on 2026-06-08 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_leavebalanceadjustment_delta_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='required_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Employee'), (2, 'Middle Management'), (3, 'Executive Management'), (4, 'Board of Directors')], help_text='Role required to act next.', null=True),
        ),
    ]
