# Generated by Django 5.2.6 on 2026-06-06 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal_letter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalletter',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='internalletter',
            name='cc',
            field=models.ManyToManyField(blank=True, related_name='cc_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalletter',
            name='parent_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='internal_letter.internalletter'),
        ),
        migrations.AlterField(
            model_name='internalletter',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalletter',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalletter',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_letters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='letterattachment',
            name='file_size',
            field=models.IntegerField(),
        ),
    ]
