"""
Django settings for companycrm project.

Generated by 'django-admin startproject' using Django 5.2.6.
"""

from pathlib import Path

# =========================
# Base Directory
# =========================
BASE_DIR = Path(__file__).resolve().parent.parent


# =========================
# Security
# =========================
SECRET_KEY = "django-insecure-d8mw3d+!wkba7wy1a3a46fazc7z81x6@t7*lx6))h_u)@&*qz("

# For local development keep True.
# For cPanel / production, change to False.
DEBUG = True

# For local development
ALLOWED_HOSTS = []

# For cPanel / production, use this instead:
# DEBUG = True
# ALLOWED_HOSTS = [
#     "yourdomain.com",
#     "www.yourdomain.com",
# ]


# =========================
# Applications
# =========================
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "rest_framework",
    "core",
    "internal_letter",
    "notifications",
     "finance"
]


# =========================
# Middleware
# =========================
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# =========================
# URL / WSGI
# =========================
ROOT_URLCONF = "companycrm.urls"

WSGI_APPLICATION = "companycrm.wsgi.application"


# =========================
# Templates
# =========================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                'core.context_processors.unread_letter_count',  # Add this line
                'core.context_processors.unread_notification_count',

            ],
        },
    },
]


# =========================
# Database
# =========================
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# =========================
# Password Validation
# =========================
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# =========================
# Internationalization
# =========================
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# =========================
# Static Files
# =========================
STATIC_URL = "/static/"

# Your project-level static folder:
# /home/imechatr/companycrm/static/
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Final collected static folder:
# /home/imechatr/companycrm/staticfiles/
STATIC_ROOT = BASE_DIR / "staticfiles"

# Use this only if WhiteNoise is installed and middleware is enabled:
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# =========================
# Authentication Redirects
# =========================
LOGIN_REDIRECT_URL = "/"

LOGOUT_REDIRECT_URL = "/accounts/login/"

LOGIN_URL = "/accounts/login/"


# =========================
# Default Primary Key
# =========================
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
# Custom admin configuration
ADMIN_SITE_HEADER = "ATO Admin Panel"
ADMIN_SITE_TITLE = "ATO Admin Panel"
ADMIN_INDEX_TITLE = "Welcome to ATO CRM Administration"

# Custom admin templates
TEMPLATES[0]['DIRS'] = [BASE_DIR / 'companycrm' / 'templates']
