# Generated by Django 5.2.6 on 2025-10-01 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_department_position_profile_departments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='approval',
            name='decided_role',
            field=models.IntegerField(choices=[(1, 'Board of Directors'), (2, 'Executive Management'), (3, 'Middle Management'), (4, 'Employee')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'Board of Directors'), (2, 'Executive Management'), (3, 'Middle Management'), (4, 'Employee')], default=4),
        ),
        migrations.AlterField(
            model_name='request',
            name='required_role',
            field=models.IntegerField(choices=[(1, 'Board of Directors'), (2, 'Executive Management'), (3, 'Middle Management'), (4, 'Employee')], default=3),
        ),
    ]
