# Generated by Django 5.2.6 on 2025-10-02 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_leaverequest_options_alter_request_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='required_role',
            field=models.IntegerField(choices=[(1, 'Employee'), (2, 'Middle Management'), (3, 'Executive Management'), (4, 'Board of Directors')], default=2, help_text='Role required to act next.'),
        ),
    ]
