# Generated by Django 6.0.6 on 2026-06-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dynamic_workflow_by_role'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='core.department'),
        ),
    ]
